### ISSUE TITLE
Failed to execute process 

### ISSUE THREAD

**Issue by dolohow** [vinibali/kingston_fw_updater#1]
Failed to execute process './kfu'. Reason:
The file './kfu' does not exist or could not be executed.

**Comment by vinibali** [comment]
Hello Dolohow!
Are you in the right directory?
Is the binary executable?

**Comment by dolohow** [comment]
>  Are you in the right directory?

I think so:
```
kingston_fw_updater-master/bin
```

> Is the binary executable?

Yes
```
-rwxr-xr-x 1 1000 1000 13M mar 18 13:45 kfu*
```

**Comment by dolohow** [comment]
Any update? :)

**Comment by vinibali** [comment]
Which distro are you using?
You might need a lot of 32bit libraries like glicb (called lib32-glibc in Arch) at least for running it.

**Comment by dolohow** [comment]
Yeah, I did not have 32 bit interpreter.

For Ubuntu 16.04 AMD64 that would be:
```
# apt install libc6-i386 libjpeg62:i386 libpng12-0:i386 libsm6:i386 libxrender1:i386 libfontconfig1:i386 libxext6:i386 lib32stdc++6
```

It works know, but it says that there are no updates.  Is your tool capable of fetching new updates or they must be provide?

**Comment by vinibali** [comment]
have you seen the readme file? it's Kingston's official tool, and the firmwares have to be stored in a numbered directory under the /custom/, just like they are under the [https://github.com/vinibali/kingston_fw_updater/tree/master/firmware](https://github.com/vinibali/kingston_fw_updater/tree/master/firmware) path.

**Comment by vinibali** [comment]
i updated the readme, you can find the AUR package's stucture there.
